networks:
  app:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: penn-entertainment
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./app:/var/www/html
    networks:
      - app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: penn-entertainment-php
    restart: always
    volumes:
      - ./app:/var/www/html
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: penn-entertainment-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: penn-entertainment
      MYSQL_USER: penn
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    networks:
      - app
    ports:
      - "3306:3306"

  composer:
    image: composer:2
    container_name: penn-entertainment-composer
    volumes:
      - ./app:/app
    working_dir: /app
    command: install
